{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "337f1754-acb6-493f-817d-a0c09d8e8f8e",
   "metadata": {},
   "source": [
    "### Question1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6dfae8e3-f1c0-41fb-9443-8a9965bfe6a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# In Python, it is recommended to use the Exception class as the base class when creating custom exceptions. Here are the reasons why:\n",
    "\n",
    "#    Consistency and Clarity: By inheriting from the Exception class, your custom exception is immediately recognizable as an exception.\n",
    "#    It conveys its purpose clearly to other developers who are familiar with the standard exception hierarchy in Python.\n",
    "\n",
    "#    Exception Handling: Python provides mechanisms for handling exceptions using try and except blocks. By deriving from Exception, your \n",
    "#    custom exception can be caught and handled in the same way as built-in exceptions. This allows for consistent and predictable \n",
    "#    exception handling in your codebase.\n",
    "\n",
    "#    Hierarchical Structure: The Exception class is at the top of the exception hierarchy in Python. It serves as the base class for all \n",
    "#    built-in exceptions, such as ValueError, TypeError, and RuntimeError. By inheriting from Exception, you can take advantage of the \n",
    "#    existing hierarchical structure and create custom exceptions that fit into the broader exception system seamlessly.\n",
    "\n",
    "#    Built-in Functionality: The Exception class provides useful functionality inherited from its parent classes, such as BaseException\n",
    "#    and object. This includes attributes like args (to store exception arguments) and methods like __str__ (to provide a string \n",
    "#    representation of the exception). By inheriting from Exception, your custom exception automatically inherits and benefits from these \n",
    "#    features.\n",
    "\n",
    "#    Code Readability and Maintainability: By using the Exception class, you follow established conventions in the Python community. \n",
    "#    This improves code readability and maintainability, as other developers familiar with Python will easily understand the purpose \n",
    "#    and behavior of your custom exception.\n",
    "\n",
    "# In summary, using the Exception class as the base class for custom exceptions in Python provides consistency, clarity, and compatibility \n",
    "# with the existing exception handling mechanisms and conventions in the language."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ec877a1a-b787-40ad-aae0-fa9508adc1f1",
   "metadata": {},
   "source": [
    "### Question2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8995a6e9-34ca-439d-98b8-a553d2e637a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python Exception Hierarchy:\n",
      "BaseException\n",
      "  Exception\n",
      "    TypeError\n",
      "      FloatOperation\n",
      "      MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "      ModuleNotFoundError\n",
      "      ZipImportError\n",
      "    OSError\n",
      "      ConnectionError\n",
      "        BrokenPipeError\n",
      "        ConnectionAbortedError\n",
      "        ConnectionRefusedError\n",
      "        ConnectionResetError\n",
      "          RemoteDisconnected\n",
      "      BlockingIOError\n",
      "      ChildProcessError\n",
      "      FileExistsError\n",
      "      FileNotFoundError\n",
      "      IsADirectoryError\n",
      "      NotADirectoryError\n",
      "      InterruptedError\n",
      "        InterruptedSystemCall\n",
      "      PermissionError\n",
      "      ProcessLookupError\n",
      "      TimeoutError\n",
      "      UnsupportedOperation\n",
      "      itimer_error\n",
      "      herror\n",
      "      gaierror\n",
      "      SSLError\n",
      "        SSLCertVerificationError\n",
      "        SSLZeroReturnError\n",
      "        SSLWantWriteError\n",
      "        SSLWantReadError\n",
      "        SSLSyscallError\n",
      "        SSLEOFError\n",
      "      Error\n",
      "        SameFileError\n",
      "      SpecialFileError\n",
      "      ExecError\n",
      "      ReadError\n",
      "      URLError\n",
      "        HTTPError\n",
      "        ContentTooShortError\n",
      "      BadGzipFile\n",
      "    EOFError\n",
      "      IncompleteReadError\n",
      "    RuntimeError\n",
      "      RecursionError\n",
      "      NotImplementedError\n",
      "        ZMQVersionError\n",
      "        StdinNotImplementedError\n",
      "      _DeadlockError\n",
      "      BrokenBarrierError\n",
      "      BrokenExecutor\n",
      "        BrokenThreadPool\n",
      "      SendfileNotAvailableError\n",
      "      ExtractionError\n",
      "      VariableError\n",
      "    NameError\n",
      "      UnboundLocalError\n",
      "    AttributeError\n",
      "      FrozenInstanceError\n",
      "    SyntaxError\n",
      "      IndentationError\n",
      "        TabError\n",
      "    LookupError\n",
      "      IndexError\n",
      "      KeyError\n",
      "        NoSuchKernel\n",
      "        UnknownBackend\n",
      "      CodecRegistryError\n",
      "    ValueError\n",
      "      UnicodeError\n",
      "        UnicodeEncodeError\n",
      "        UnicodeDecodeError\n",
      "        UnicodeTranslateError\n",
      "      UnsupportedOperation\n",
      "      JSONDecodeError\n",
      "      SSLCertVerificationError\n",
      "      Error\n",
      "      UnsupportedDigestmodError\n",
      "      IllegalMonthError\n",
      "      IllegalWeekdayError\n",
      "      ParserError\n",
      "      ClassNotFound\n",
      "      ClipboardEmpty\n",
      "      MessageDefect\n",
      "        NoBoundaryInMultipartDefect\n",
      "        StartBoundaryNotFoundDefect\n",
      "        CloseBoundaryNotFoundDefect\n",
      "        FirstHeaderLineIsContinuationDefect\n",
      "        MisplacedEnvelopeHeaderDefect\n",
      "        MissingHeaderBodySeparatorDefect\n",
      "        MultipartInvariantViolationDefect\n",
      "        InvalidMultipartContentTransferEncodingDefect\n",
      "        UndecodableBytesDefect\n",
      "        InvalidBase64PaddingDefect\n",
      "        InvalidBase64CharactersDefect\n",
      "        InvalidBase64LengthDefect\n",
      "        HeaderDefect\n",
      "          InvalidHeaderDefect\n",
      "          HeaderMissingRequiredValue\n",
      "          NonPrintableDefect\n",
      "          ObsoleteHeaderDefect\n",
      "          NonASCIILocalPartDefect\n",
      "          InvalidDateDefect\n",
      "      MacroToEdit\n",
      "      InvalidFileException\n",
      "      UnequalIterablesError\n",
      "      InvalidVersion\n",
      "      _InvalidELFFileHeader\n",
      "      InvalidWheelFilename\n",
      "      InvalidSdistFilename\n",
      "      InvalidSpecifier\n",
      "      InvalidMarker\n",
      "      UndefinedComparison\n",
      "      UndefinedEnvironmentName\n",
      "      InvalidRequirement\n",
      "        RequirementParseError\n",
      "      InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "      FloatingPointError\n",
      "      OverflowError\n",
      "      ZeroDivisionError\n",
      "        DivisionByZero\n",
      "        DivisionUndefined\n",
      "      DecimalException\n",
      "        Clamped\n",
      "        Rounded\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Inexact\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Subnormal\n",
      "          Underflow\n",
      "        DivisionByZero\n",
      "        FloatOperation\n",
      "        InvalidOperation\n",
      "          ConversionSyntax\n",
      "          DivisionImpossible\n",
      "          DivisionUndefined\n",
      "          InvalidContext\n",
      "    SystemError\n",
      "      CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "      UserWarning\n",
      "        GetPassWarning\n",
      "        FormatterWarning\n",
      "      EncodingWarning\n",
      "      DeprecationWarning\n",
      "        ProvisionalWarning\n",
      "      PendingDeprecationWarning\n",
      "      SyntaxWarning\n",
      "      RuntimeWarning\n",
      "        ProactorSelectorThreadWarning\n",
      "        UnknownTimezoneWarning\n",
      "        PEP440Warning\n",
      "      FutureWarning\n",
      "        ProvisionalCompleterWarning\n",
      "      ImportWarning\n",
      "      UnicodeWarning\n",
      "      BytesWarning\n",
      "      ResourceWarning\n",
      "      DeprecatedTzFormatWarning\n",
      "      PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "      CalledProcessError\n",
      "      TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "      CancelledError\n",
      "      TimeoutError\n",
      "      InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "      ZMQError\n",
      "        ContextTerminated\n",
      "        Again\n",
      "        InterruptedSystemCall\n",
      "      ZMQBindError\n",
      "      NotDone\n",
      "    PickleError\n",
      "      PicklingError\n",
      "      UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "      ConfigLoaderError\n",
      "        ArgumentError\n",
      "      ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "      MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "      NoSectionError\n",
      "      DuplicateSectionError\n",
      "      DuplicateOptionError\n",
      "      NoOptionError\n",
      "      InterpolationError\n",
      "        InterpolationMissingOptionError\n",
      "        InterpolationSyntaxError\n",
      "        InterpolationDepthError\n",
      "      ParsingError\n",
      "        MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "      EOF\n",
      "      TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "      TryNext\n",
      "      UsageError\n",
      "      StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "      InvalidAliasError\n",
      "    Error\n",
      "      InterfaceError\n",
      "      DatabaseError\n",
      "        InternalError\n",
      "        OperationalError\n",
      "        ProgrammingError\n",
      "        IntegrityError\n",
      "        DataError\n",
      "        NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "      IndexSizeErr\n",
      "      DomstringSizeErr\n",
      "      HierarchyRequestErr\n",
      "      WrongDocumentErr\n",
      "      InvalidCharacterErr\n",
      "      NoDataAllowedErr\n",
      "      NoModificationAllowedErr\n",
      "      NotFoundErr\n",
      "      NotSupportedErr\n",
      "      InuseAttributeErr\n",
      "      InvalidStateErr\n",
      "      SyntaxErr\n",
      "      InvalidModificationErr\n",
      "      NamespaceErr\n",
      "      InvalidAccessErr\n",
      "      ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "      InternalError\n",
      "      WrongVersion\n",
      "      RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "      MessageParseError\n",
      "        HeaderParseError\n",
      "        BoundaryError\n",
      "      MultipartConversionError\n",
      "      CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "      NotConnected\n",
      "      InvalidURL\n",
      "      UnknownProtocol\n",
      "      UnknownTransferEncoding\n",
      "      UnimplementedFileMode\n",
      "      IncompleteRead\n",
      "      ImproperConnectionState\n",
      "        CannotSendRequest\n",
      "        CannotSendHeader\n",
      "        ResponseNotReady\n",
      "      BadStatusLine\n",
      "        RemoteDisconnected\n",
      "      LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "      NoSuchProcess\n",
      "        ZombieProcess\n",
      "      AccessDenied\n",
      "      TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "      ProtocolError\n",
      "      ResponseError\n",
      "      Fault\n",
      "    ParseBaseException\n",
      "      ParseException\n",
      "      ParseFatalException\n",
      "        ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "      VersionConflict\n",
      "        ContextualVersionConflict\n",
      "      DistributionNotFound\n",
      "      UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n",
      "  GeneratorExit\n",
      "  SystemExit\n",
      "  KeyboardInterrupt\n",
      "  CancelledError\n",
      "  AbortThread\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(\"  \" * indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 1)\n",
    "\n",
    "print(\"Python Exception Hierarchy:\")\n",
    "print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ce7da589-88ab-458e-98d6-81bc9bcb57c9",
   "metadata": {},
   "source": [
    "### Question3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "cd8b5cca-3086-4d1d-9fb7-a6e0a1f0f26a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "# The ArithmeticError class in Python represents errors that occur during arithmetic operations. It serves as the base class for several\n",
    "# specific arithmetic-related exceptions. Here are two examples of errors defined in the ArithmeticError class, along with explanations \n",
    "# and code examples:\n",
    "\n",
    "#    ZeroDivisionError: This error is raised when a division or modulo operation is performed with zero as the divisor.\n",
    "\n",
    "#Example:\n",
    "try:\n",
    "    result = 10 / 0  # Dividing by zero\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"Error:\", e)\n",
    "# OverflowError: This error is raised when the result of an arithmetic operation exceeds the range of representable values.\n",
    "try:\n",
    "    result = 10 ** 10000  # Performing exponentiation with a large exponent\n",
    "except OverflowError as e:\n",
    "    print(\"Error:\", e)\n",
    "# Both ZeroDivisionError and OverflowError are subclasses of ArithmeticError. They provide specific error handling for scenarios where\n",
    "# division by zero occurs or the result of an arithmetic operation goes beyond the representable range. By catching these exceptions, \n",
    "# you can handle such situations gracefully and prevent your program from terminating unexpectedly."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "13c0c54c-96c0-4337-8610-ec67b77f491f",
   "metadata": {},
   "source": [
    "### Question4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ec9c2a98-c10a-4d72-a86a-a973f3f5d512",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: 'gender'\n",
      "Error: list index out of range\n"
     ]
    }
   ],
   "source": [
    "# The LookupError class in Python is used to handle errors that occur when a lookup operation fails. It serves as the base class for \n",
    "# exceptions related to indexing and key lookup operations. Here are two examples of errors defined in the LookupError class, along\n",
    "# with explanations and code examples:\n",
    "\n",
    "#    KeyError: This error is raised when a dictionary or mapping key is not found\n",
    "my_dict = {'name': 'John', 'age': 25}\n",
    "\n",
    "try:\n",
    "    value = my_dict['gender']  # Accessing a non-existent key\n",
    "except KeyError as e:\n",
    "    print(\"Error:\", e)\n",
    "# IndexError: This error is raised when an index used for accessing elements in a sequence (such as a list or tuple) is out of range.\n",
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[3]  # Accessing an out-of-range index\n",
    "except IndexError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c2814b49-d417-4a3c-8219-a5bb72781760",
   "metadata": {},
   "source": [
    "### Question5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4b23a1cf-452f-4d01-96b2-ee04149144f6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: No module named 'non_existent_module'\n",
      "Error: No module named 'non_existent_package'\n"
     ]
    }
   ],
   "source": [
    "# In Python, ImportError and ModuleNotFoundError are exceptions that occur when there are issues with importing modules. Here's an \n",
    "# explanation of each:\n",
    "\n",
    "#  ImportError: This exception is raised when an imported module cannot be found or when there is an error during the import process.\n",
    "try:\n",
    "    import non_existent_module  # Trying to import a non-existent module\n",
    "except ImportError as e:\n",
    "    print(\"Error:\", e)\n",
    "# ModuleNotFoundError: This exception is a subclass of ImportError and specifically raised when a module cannot be found during the \n",
    "# import process.\n",
    "try:\n",
    "    from non_existent_package import module_name  # Trying to import a module from a non-existent package\n",
    "except ModuleNotFoundError as e:\n",
    "    print(\"Error:\", e)\n",
    "# In summary, ImportError is a general exception that covers errors related to importing modules, while ModuleNotFoundError is a more \n",
    "# specific subclass of ImportError that specifically indicates that a module or package cannot be found during the import process. \n",
    "# These exceptions help in handling import-related issues and provide information about what went wrong when importing modules in Python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e365fe7a-f038-4395-8ff5-65efbcb36b97",
   "metadata": {},
   "source": [
    "### Question6"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "17efe336-546f-45d4-bf71-2c5c7d34cab0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Specific Exception Handling: Handle exceptions at the appropriate level of granularity. Catch specific exceptions rather than using\n",
    "# broad exception handlers like except Exception:. This allows for targeted error handling and avoids unintentionally catching and \n",
    "# suppressing unrelated exceptions.\n",
    "\n",
    "# Use Multiple Except Clauses: When handling multiple exceptions, use separate except clauses for each exception rather than catching \n",
    "# multiple exceptions in a single clause. This makes the code more readable and allows for specific error handling for each exception.\n",
    "\n",
    "# Avoid Bare Except Clauses: Avoid using bare except clauses without specifying the exception type. It can lead to hiding or misinterpreting \n",
    "# errors. Instead, catch specific exceptions or use a generic except Exception as e: clause to handle unexpected errors while logging \n",
    "# or reporting them appropriately.\n",
    "\n",
    "# Cleanup with Finally: Use the finally block to ensure that critical cleanup code, such as releasing resources or closing files, is \n",
    "# executed regardless of whether an exception occurred or not. This helps maintain the integrity of the system and prevents resource leaks.\n",
    "\n",
    "# Raising Exceptions: Raise exceptions with meaningful error messages that provide useful information about the nature of the error. \n",
    "# Include relevant details such as values, context, or stack trace information to aid in debugging and troubleshooting.\n",
    "\n",
    "# Logging Exceptions: Consider using a logging framework, such as Python's logging module, to log exceptions. This helps in identifying \n",
    "# and diagnosing issues, especially in production environments. Log relevant details like the exception type, error message, and any \n",
    "# additional context information.\n",
    "\n",
    "# Avoid Silent Failures: Avoid silently ignoring exceptions without any appropriate handling or logging. If an exception occurs and cannot\n",
    "# be handled, it is generally better to let it propagate up the call stack or exit the program gracefully, rather than continuing with \n",
    "# potentially corrupted or incorrect data."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
